name: Add issue to Priorities board
on:
  issues:
    types: [opened, reopened, transferred]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/team-monet/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
